name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      create-acr:
        type: boolean
        default: true
      create-appgateway:
        type: boolean
        default: true
 
jobs:
  create-acr:
    if: ${{ github.event.inputs.create-acr == 'true' }}
    runs-on: ubuntu-latest
    name: Create ACR
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/acr
        id: acr
        with: 
          acr-name: 'myacr'
          run-step: false
      - name: Output ACR URL
        run: echo "The ACR URL is ${{ steps.acr.outputs.url }}"
  create-appgateway:
    if: ${{ github.event.inputs.create-appgateway == 'true' }}
    runs-on: ubuntu-latest
    name: Create App Gateway
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "... app gateway stuff"
