on: 
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: test
      run: |
        env
        echo ${{ env.AZURE_CLIENT_ID }}

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Function Publish
      uses: Azure/functions-action@v1
      with:
        app-name: actions-playground-tjcorr
        package: 'function/'