on: 
  workflow_dispatch:
    inputs:
      build-code:
        description: 'Build the application'
        required: true
        type: boolean
        default: true
      publish-code:
        description: 'Publish the application artifact'
        required: true
        type: boolean
        default: false
      deploy-infra:
        description: 'Deploy the infrastructure to Azure'
        required: true
        type: boolean
        default: false
      env:
        description: 'Which environment to deploy to'
        required: true
        type: string

jobs:
  parse-variables:
    runs-on: ubuntu-latest
    outputs: 
      variables: ${{ steps.parse-variables.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/parse-variable
        id: parse-variables
        with: 
          path: ".github/variables/var-${{ github.event.inputs.env }}.env"
          run-step: false
      - name: Output ACR Name
        run: echo "The ACR name is ${{ steps.parse-variables.outputs.AcrName }}"
      - name: Output ACR Name 2
        run: echo "The ACR name is ${{steps.parse-variables.outputs.json}}"
      - name: Output ACR Name 4
        run: echo "The ACR name is ${{fromJSON(steps.parse-variables.outputs.json)}}"
      - name: Output ACR Name 4
        run: echo "The ACR name is ${{fromJSON(steps.parse-variables.outputs.json.AcrName)}}"
    
  build-code:
    needs: [parse-variables]
    if: ${{ github.event.inputs.build-code == 'true' }}
    uses: ./.github/workflows/build-code.yml
    
  deploy-infra:
    needs: [parse-variables]
    if: ${{ github.event.inputs.deploy-infra == 'true' }}
    uses: ./.github/workflows/deploy-infra.yml
    with:
      create-acr: true
      create-appgateway: false
      acr-name: ${{fromJSON(needs.parse-variables.output.variables.AcrName)}}
      
  publish-code:
    needs: [build-code, deploy-infra]
    if: ${{ always() && github.event.inputs.publish-code == 'true'}}
    uses: ./.github/workflows/publish-code.yml

