on: 
  workflow_dispatch:
    inputs:
      build-code:
        description: 'Build the application'
        required: true
        type: boolean
        default: true
      publish-code:
        description: 'Publish the application artifact'
        required: true
        type: boolean
        default: false
      deploy-infra:
        description: 'Deploy the infrastructure to Azure'
        required: true
        type: boolean
        default: false

jobs:
  build-code:
    if: ${{ github.event.inputs.build-code == 'true' }}
    uses: ./.github/workflows/build-code.yml
  publish-code:
    if: ${{ github.event.inputs.publish-code == 'true' }}
    uses: ./.github/workflows/publish-code.yml
  deploy-infra:
    if: ${{ github.event.inputs.deploy-infra == 'true' }}
    uses: ./.github/workflows/deploy-infra.yml
    with:
      create-appgateway: false
