on: 
  workflow_dispatch:

jobs:
  create-acr:
    runs-on: ubuntu-latest
    name: Create ACR
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/acr
        with: 
          acr-name: 'myacr'
