on: 
  workflow_dispatch:
    inputs:
      build-code:
        description: 'Build the application'
        required: true
        type: boolean
        default: true
      publish-code:
        description: 'Publish the application artifact'
        required: true
        type: boolean
        default: false
      deploy-infra:
        description: 'Deploy the infrastructure to Azure'
        required: true
        type: boolean
        default: false
      env:
        description: 'Which environment to deploy to'
        required: true
        type: string

jobs:
  parse-variables:
    
  build-code:
    if: ${{ github.event.inputs.build-code == 'true' }}
    uses: ./.github/workflows/build-code.yml
    
  deploy-infra:
    if: ${{ github.event.inputs.deploy-infra == 'true' }}
    uses: ./.github/workflows/deploy-infra.yml
    with:
      create-acr: true
      create-appgateway: false
      
  publish-code:
    needs: [build-code, deploy-infra]
    if: ${{ always() && github.event.inputs.publish-code == 'true'}}
    uses: ./.github/workflows/publish-code.yml

