on: 
  workflow_dispatch:
    inputs:
      build-code:
        description: 'Build the application'
        required: true
        type: boolean
        default: true
      publish-code:
        description: 'Publish the application artifact'
        required: true
        type: boolean
        default: false
      deploy-infra:
        description: 'Deploy the infrastructure to Azure'
        required: true
        type: boolean
        default: false

jobs:
  create-acr:
    runs-on: ubuntu-latest
    name: Create ACR
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/acr
        id: acr
        with: 
          acr-name: 'myacr'
          run-step: false
      - name: Output ACR URL
        run: echo "The ACR URL is ${{ steps.acr.outputs.url }}"
