on: 
  workflow_dispatch:
  
jobs:
  pac:
    runs-on: windows-latest
    steps:
      - name: install pac
        run: |
          curl.exe -L --output pac.msi --url https://aka.ms/PowerAppsCLI
          msiexec /i /qn pac.msi
          pac --help
