name: Runs On with Environment Variable

on:
  workflow_dispatch:
  
env:
  OS: ubuntu-latest
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.env.outputs.env }}
    steps: 
    - name: env
      run: echo "::set-output name=env::$(echo $OS)"
  test:
    needs: [ setup ]
    runs-on: ${{ needs.setup.outputs.os }}
    steps:
    - run: echo hello
