on: 
  workflow_dispatch:
    inputs:
      build-code:
        description: 'Build the application'
        required: true
        type: boolean
        default: true
      publish-code:
        description: 'Publish the application artifact'
        required: true
        type: boolean
        default: false
      deploy-infra:
        description: 'Deploy the infrastructure to Azure'
        required: true
        type: boolean
        default: false
jobs:

  build-code:
    if: ${{ github.event.inputs.build-code == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo build
    
  deploy-infra:
    if: ${{ github.event.inputs.deploy-infra == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy
      
  publish-code:
    needs: [build-code, deploy-infra]
    if: ${{ github.event.inputs.publish-code == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo publish
